name: zendesk_plugin_plus
description: A Flutter plugin for the Zendesk Chat SDK v2. Provides embed chat functionality in your apps to give your mobile users access to your support team
version: 2.1.0
homepage: https://github.com/Tetsukick/zendesk_plugin

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.teppei.kikuchi.zendesk.plugin
        pluginClass: ZendeskPlugin
      ios:
        pluginClass: ZendeskPlugin
